name:                haskellings
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/asarkar/haskellings#readme
license:             "Apache-2.0"
author:              "Abhijit Sarkar"
copyright:           "2025 Abhijit Sarkar"

extra-source-files:
- README.md
- LICENSE

dependencies:
  - base > 4 && < 5

default-extensions:
- TupleSections
- DerivingStrategies
- InstanceSigs

ghc-options:
- -Werror
# For details on warnings: https://downloads.haskell.org/~ghc/master/users-guide/using-warnings.html
# This list originally taken from https://medium.com/mercury-bank/enable-all-the-warnings-a0517bc081c3
# Enable all warnings with -Weverything, then disable the ones we don’t care about
- -Weverything
- -Wno-missing-import-lists  # Requires explicit imports of _every_ function (e.g. ‘$’); too strict
- -Wno-missed-specializations  # When GHC can’t specialize a polymorphic function. No big deal and requires fixing underlying libraries to solve.
- -Wno-all-missed-specializations  # See missed-specialisations
- -Wno-missing-local-signatures  # Warning for polymorphic local bindings; nothing wrong with those.
- -Wno-monomorphism-restriction  # Don’t warn if the monomorphism restriction is used.
- -Wno-missing-safe-haskell-mode  # Never heard of it.
- -Wno-safe
- -Wno-unsafe
- -Wno-implicit-prelude  # In most cases, we want Prelude implicitly imported.
- -Wno-prepositive-qualified-module
- -Wno-missing-kind-signatures
- -Wno-unused-top-binds
- -Wno-missing-export-lists
- -Wno-missing-role-annotations
- -Wno-type-defaults
- -Wno-x-partial

library:
  source-dirs: src
  # dependencies:
  #   - containers

tests:
  haskellings-test:
    main: Driver.hs
    source-dirs: test
    build-tools:
    - tasty-discover:tasty-discover
    dependencies:
    - haskellings
    - tasty
    - tasty-hunit
